version: '3.8'
services:
  nextjs_app:
    build:
      context: ./app/electronic_article_sales
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
    volumes:
      - ./app/electronic_article_sales:/app
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true