version: '3.8'
services:
  nextjs_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true